import os
from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext
from Cython.Build import cythonize
from Cython.Compiler import Options

os.environ["CXX"] = "g++-13"
Options.docstrings = True

extensions = [
    Extension(
        name="tokkit.tokenizer",  # This is the import name: `import tokenizer`
        sources=[
            "src/tokkit/bindings/tokenizer.pyx",
            "src/tokkit/cpp/tokenizer.cpp",
            "src/tokkit/cpp/data.cpp",
        ],  # Don't include .cpp manually unless it's NOT generated by Cython
        include_dirs=[
            "src/tokkit/cpp",
            # "src/tokkit"
        ],
        language="c++",  # Important: tell setuptools to use a C++ compiler
        extra_compile_args=[
            "-std=c++23"
        ],  # Or c++17/c++20, if needed
    )
]

setup(
    name="tokkit",
    packages=[
        "src"
    ],
    ext_modules=cythonize(
        extensions,
        language_level=3,
        compiler_directives={"embedsignature": True},
    ),
    zip_safe=False,
    cmdclass={"build_ext": build_ext},
)
