name: Upload Python Package Mac

on:
  release:
    types: [published]
  # push:
  #   branches:
  #     - main

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel

    - name: Build macos wheels with cibuildwheel
      run: |
        cibuildwheel --output-dir dist --platform macos

    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*

  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - name: Publish to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
