name: Upload Python Package

on:
  release:
    types: [published]
  # push:
  #   branches:
  #     - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel

    - name: Build wheels with cibuildwheel
      run: |
        cibuildwheel --output-dir dist
        
      env:
        CIBW_BUILD: "cp310-* cp311-* cp312-*"
        CIBW_SKIP: "*-musllinux*"
        CIBW_ARCHS_LINUX: x86_64
        # 👇 Inject g++-13 into Linux builds only
        CIBW_BEFORE_BUILD_LINUX: |
          apt-get update && apt-get install -y g++-13

    - name: Publish to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}